### ISSUE TITLE
Bug: figma use font input i'm error

### ISSUE THREAD

**Issue by iusx** [iepn/tsing-font#8]
## Description

<img width="685" alt="image" src="https://github.com/iepn/tsing-font/assets/57232813/79d2ef7e-a410-4aa4-980e-7819a7ae67cc">

## Screenshots or Error Messages

<img width="1206" alt="image" src="https://github.com/iepn/tsing-font/assets/57232813/40da16d1-fd99-47be-8317-fe8a55291c51">

**Comment by iepn** [comment]
<img width="561" alt="image" src="https://github.com/iepn/tsing-font/assets/57232813/f219b9eb-a5ec-4af9-bff1-fbd3d43abe4b">

**Comment by iusx** [comment]
<img width="875" alt="image" src="https://github.com/iepn/tsing-font/assets/57232813/32a7cee4-bcf7-40fb-83b6-f779c8fa673f">
